# This is the config file for pufferblow-api
# please if you do edit this file you will need
# to restart, in order to apply the changes

[api]
host = "0.0.0.0"
port = 7575
logs_path = "{HOME}/pufferblow_api.log"
workers = 7 # number of workers for guvicorn, the higher the better
rate_limit_duration = 5 # the duration of a rate limit of an IP address (in minutes)
max_rate_limit_requests = 6000 # number of request before a rate limit warning
max_rate_limit_warnings = 15 # number of rate limit warnings before blocking the IP address

[supabase]
supabase_url = "<your supabase url>"
supabase_key = "<your supabase key>"

[supabase.postregsql]
database_name = "<your database name>"
username = "<your username>"
password = "<your password>"
host = "<your database host>"
port = "<your database port>"

[encryption]
derived_key_bytes = 56 # This specifies the bytes length of the derived key. A 56-bit key provides a good balance between security and performance. The bytes should be 5 to 56 bytes.
derived_key_rounds = 100 # This represents the number of iterations for the derived key generation process. A higher value increases the computational effort required, enhancing security but also using more CPU resources.
salt_rounds = 18 # This represents the number of iterations for the salt generation process. A higher value increases the computational effort required, enhancing security but also using more CPU resources.

[messages]
max_message_size = 1024 # This defines the maximum size (in KB) for a message that can be sent. Setting this to a larger value may provide more flexibility, but it could also impact your storage capacity. Please adjust according to your storage resources.
max_messages_per_page = 50 # This defines the maximum number of messages that can be displayed on each page. A value of 50 is recommended to balance between data load and user experience.
min_messages_per_page = 20 # This defines the minimum number of messages that can be displayed on each page. A value of 20 is recommended to ensure that there is enough message for the user to engage with on each page.

[server_info]
server_sha256 = "<your server's sha256>" # Unique identifier for this server. Auto generated, do not change it!
server_name = "<your server name>"
server_description = "<your server description>"
server_avatar_url = "<url to your server avatar/photo>"
server_maintainer_name = "<the name of the server maintainer, it can be the name of the server owner>"
server_welcome_message = "<your server's welcome message, will be returned when a GET requests goes to http://<host>:<port>/api/v1>"
